// Generated by gencpp from file autopilot_bridge/FenceSetAll.msg
// DO NOT EDIT!


#ifndef AUTOPILOT_BRIDGE_MESSAGE_FENCESETALL_H
#define AUTOPILOT_BRIDGE_MESSAGE_FENCESETALL_H

#include <ros/service_traits.h>


#include <autopilot_bridge/FenceSetAllRequest.h>
#include <autopilot_bridge/FenceSetAllResponse.h>


namespace autopilot_bridge
{

struct FenceSetAll
{

typedef FenceSetAllRequest Request;
typedef FenceSetAllResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FenceSetAll
} // namespace autopilot_bridge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::autopilot_bridge::FenceSetAll > {
  static const char* value()
  {
    return "f88ef42c3c089842e6bb8c2306bcba9b";
  }

  static const char* value(const ::autopilot_bridge::FenceSetAll&) { return value(); }
};

template<>
struct DataType< ::autopilot_bridge::FenceSetAll > {
  static const char* value()
  {
    return "autopilot_bridge/FenceSetAll";
  }

  static const char* value(const ::autopilot_bridge::FenceSetAll&) { return value(); }
};


// service_traits::MD5Sum< ::autopilot_bridge::FenceSetAllRequest> should match 
// service_traits::MD5Sum< ::autopilot_bridge::FenceSetAll > 
template<>
struct MD5Sum< ::autopilot_bridge::FenceSetAllRequest>
{
  static const char* value()
  {
    return MD5Sum< ::autopilot_bridge::FenceSetAll >::value();
  }
  static const char* value(const ::autopilot_bridge::FenceSetAllRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::autopilot_bridge::FenceSetAllRequest> should match 
// service_traits::DataType< ::autopilot_bridge::FenceSetAll > 
template<>
struct DataType< ::autopilot_bridge::FenceSetAllRequest>
{
  static const char* value()
  {
    return DataType< ::autopilot_bridge::FenceSetAll >::value();
  }
  static const char* value(const ::autopilot_bridge::FenceSetAllRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::autopilot_bridge::FenceSetAllResponse> should match 
// service_traits::MD5Sum< ::autopilot_bridge::FenceSetAll > 
template<>
struct MD5Sum< ::autopilot_bridge::FenceSetAllResponse>
{
  static const char* value()
  {
    return MD5Sum< ::autopilot_bridge::FenceSetAll >::value();
  }
  static const char* value(const ::autopilot_bridge::FenceSetAllResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::autopilot_bridge::FenceSetAllResponse> should match 
// service_traits::DataType< ::autopilot_bridge::FenceSetAll > 
template<>
struct DataType< ::autopilot_bridge::FenceSetAllResponse>
{
  static const char* value()
  {
    return DataType< ::autopilot_bridge::FenceSetAll >::value();
  }
  static const char* value(const ::autopilot_bridge::FenceSetAllResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTOPILOT_BRIDGE_MESSAGE_FENCESETALL_H
