// Generated by gencpp from file autopilot_bridge/FenceGetAll.msg
// DO NOT EDIT!


#ifndef AUTOPILOT_BRIDGE_MESSAGE_FENCEGETALL_H
#define AUTOPILOT_BRIDGE_MESSAGE_FENCEGETALL_H

#include <ros/service_traits.h>


#include <autopilot_bridge/FenceGetAllRequest.h>
#include <autopilot_bridge/FenceGetAllResponse.h>


namespace autopilot_bridge
{

struct FenceGetAll
{

typedef FenceGetAllRequest Request;
typedef FenceGetAllResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FenceGetAll
} // namespace autopilot_bridge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::autopilot_bridge::FenceGetAll > {
  static const char* value()
  {
    return "3af4de476ae820ab7043ee91d5577ce1";
  }

  static const char* value(const ::autopilot_bridge::FenceGetAll&) { return value(); }
};

template<>
struct DataType< ::autopilot_bridge::FenceGetAll > {
  static const char* value()
  {
    return "autopilot_bridge/FenceGetAll";
  }

  static const char* value(const ::autopilot_bridge::FenceGetAll&) { return value(); }
};


// service_traits::MD5Sum< ::autopilot_bridge::FenceGetAllRequest> should match 
// service_traits::MD5Sum< ::autopilot_bridge::FenceGetAll > 
template<>
struct MD5Sum< ::autopilot_bridge::FenceGetAllRequest>
{
  static const char* value()
  {
    return MD5Sum< ::autopilot_bridge::FenceGetAll >::value();
  }
  static const char* value(const ::autopilot_bridge::FenceGetAllRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::autopilot_bridge::FenceGetAllRequest> should match 
// service_traits::DataType< ::autopilot_bridge::FenceGetAll > 
template<>
struct DataType< ::autopilot_bridge::FenceGetAllRequest>
{
  static const char* value()
  {
    return DataType< ::autopilot_bridge::FenceGetAll >::value();
  }
  static const char* value(const ::autopilot_bridge::FenceGetAllRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::autopilot_bridge::FenceGetAllResponse> should match 
// service_traits::MD5Sum< ::autopilot_bridge::FenceGetAll > 
template<>
struct MD5Sum< ::autopilot_bridge::FenceGetAllResponse>
{
  static const char* value()
  {
    return MD5Sum< ::autopilot_bridge::FenceGetAll >::value();
  }
  static const char* value(const ::autopilot_bridge::FenceGetAllResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::autopilot_bridge::FenceGetAllResponse> should match 
// service_traits::DataType< ::autopilot_bridge::FenceGetAll > 
template<>
struct DataType< ::autopilot_bridge::FenceGetAllResponse>
{
  static const char* value()
  {
    return DataType< ::autopilot_bridge::FenceGetAll >::value();
  }
  static const char* value(const ::autopilot_bridge::FenceGetAllResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTOPILOT_BRIDGE_MESSAGE_FENCEGETALL_H
