// Generated by gencpp from file autopilot_bridge/ParamSet.msg
// DO NOT EDIT!


#ifndef AUTOPILOT_BRIDGE_MESSAGE_PARAMSET_H
#define AUTOPILOT_BRIDGE_MESSAGE_PARAMSET_H

#include <ros/service_traits.h>


#include <autopilot_bridge/ParamSetRequest.h>
#include <autopilot_bridge/ParamSetResponse.h>


namespace autopilot_bridge
{

struct ParamSet
{

typedef ParamSetRequest Request;
typedef ParamSetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ParamSet
} // namespace autopilot_bridge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::autopilot_bridge::ParamSet > {
  static const char* value()
  {
    return "762cb7cc4dabef610b8749b068c8bb92";
  }

  static const char* value(const ::autopilot_bridge::ParamSet&) { return value(); }
};

template<>
struct DataType< ::autopilot_bridge::ParamSet > {
  static const char* value()
  {
    return "autopilot_bridge/ParamSet";
  }

  static const char* value(const ::autopilot_bridge::ParamSet&) { return value(); }
};


// service_traits::MD5Sum< ::autopilot_bridge::ParamSetRequest> should match 
// service_traits::MD5Sum< ::autopilot_bridge::ParamSet > 
template<>
struct MD5Sum< ::autopilot_bridge::ParamSetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::autopilot_bridge::ParamSet >::value();
  }
  static const char* value(const ::autopilot_bridge::ParamSetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::autopilot_bridge::ParamSetRequest> should match 
// service_traits::DataType< ::autopilot_bridge::ParamSet > 
template<>
struct DataType< ::autopilot_bridge::ParamSetRequest>
{
  static const char* value()
  {
    return DataType< ::autopilot_bridge::ParamSet >::value();
  }
  static const char* value(const ::autopilot_bridge::ParamSetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::autopilot_bridge::ParamSetResponse> should match 
// service_traits::MD5Sum< ::autopilot_bridge::ParamSet > 
template<>
struct MD5Sum< ::autopilot_bridge::ParamSetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::autopilot_bridge::ParamSet >::value();
  }
  static const char* value(const ::autopilot_bridge::ParamSetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::autopilot_bridge::ParamSetResponse> should match 
// service_traits::DataType< ::autopilot_bridge::ParamSet > 
template<>
struct DataType< ::autopilot_bridge::ParamSetResponse>
{
  static const char* value()
  {
    return DataType< ::autopilot_bridge::ParamSet >::value();
  }
  static const char* value(const ::autopilot_bridge::ParamSetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTOPILOT_BRIDGE_MESSAGE_PARAMSET_H
