// Generated by gencpp from file autopilot_bridge/ParamGetResponse.msg
// DO NOT EDIT!


#ifndef AUTOPILOT_BRIDGE_MESSAGE_PARAMGETRESPONSE_H
#define AUTOPILOT_BRIDGE_MESSAGE_PARAMGETRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autopilot_bridge
{
template <class ContainerAllocator>
struct ParamGetResponse_
{
  typedef ParamGetResponse_<ContainerAllocator> Type;

  ParamGetResponse_()
    : ok(false)
    , value(0.0)  {
    }
  ParamGetResponse_(const ContainerAllocator& _alloc)
    : ok(false)
    , value(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _ok_type;
  _ok_type ok;

   typedef double _value_type;
  _value_type value;




  typedef boost::shared_ptr< ::autopilot_bridge::ParamGetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autopilot_bridge::ParamGetResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ParamGetResponse_

typedef ::autopilot_bridge::ParamGetResponse_<std::allocator<void> > ParamGetResponse;

typedef boost::shared_ptr< ::autopilot_bridge::ParamGetResponse > ParamGetResponsePtr;
typedef boost::shared_ptr< ::autopilot_bridge::ParamGetResponse const> ParamGetResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autopilot_bridge::ParamGetResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autopilot_bridge::ParamGetResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace autopilot_bridge

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'autopilot_bridge': ['/home/osboxes/ACS/acs_ros_ws/src/autopilot_bridge/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::autopilot_bridge::ParamGetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autopilot_bridge::ParamGetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autopilot_bridge::ParamGetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autopilot_bridge::ParamGetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autopilot_bridge::ParamGetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autopilot_bridge::ParamGetResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autopilot_bridge::ParamGetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "68837705d961339ea8048dd1e5789cea";
  }

  static const char* value(const ::autopilot_bridge::ParamGetResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x68837705d961339eULL;
  static const uint64_t static_value2 = 0xa8048dd1e5789ceaULL;
};

template<class ContainerAllocator>
struct DataType< ::autopilot_bridge::ParamGetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autopilot_bridge/ParamGetResponse";
  }

  static const char* value(const ::autopilot_bridge::ParamGetResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autopilot_bridge::ParamGetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ok\n\
float64 value\n\
\n\
";
  }

  static const char* value(const ::autopilot_bridge::ParamGetResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autopilot_bridge::ParamGetResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ParamGetResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autopilot_bridge::ParamGetResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autopilot_bridge::ParamGetResponse_<ContainerAllocator>& v)
  {
    s << indent << "ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ok);
    s << indent << "value: ";
    Printer<double>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOPILOT_BRIDGE_MESSAGE_PARAMGETRESPONSE_H
