// Generated by gencpp from file autopilot_bridge/ParamSetList.msg
// DO NOT EDIT!


#ifndef AUTOPILOT_BRIDGE_MESSAGE_PARAMSETLIST_H
#define AUTOPILOT_BRIDGE_MESSAGE_PARAMSETLIST_H

#include <ros/service_traits.h>


#include <autopilot_bridge/ParamSetListRequest.h>
#include <autopilot_bridge/ParamSetListResponse.h>


namespace autopilot_bridge
{

struct ParamSetList
{

typedef ParamSetListRequest Request;
typedef ParamSetListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ParamSetList
} // namespace autopilot_bridge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::autopilot_bridge::ParamSetList > {
  static const char* value()
  {
    return "7c20195a6434b00060c5d34397ef8702";
  }

  static const char* value(const ::autopilot_bridge::ParamSetList&) { return value(); }
};

template<>
struct DataType< ::autopilot_bridge::ParamSetList > {
  static const char* value()
  {
    return "autopilot_bridge/ParamSetList";
  }

  static const char* value(const ::autopilot_bridge::ParamSetList&) { return value(); }
};


// service_traits::MD5Sum< ::autopilot_bridge::ParamSetListRequest> should match 
// service_traits::MD5Sum< ::autopilot_bridge::ParamSetList > 
template<>
struct MD5Sum< ::autopilot_bridge::ParamSetListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::autopilot_bridge::ParamSetList >::value();
  }
  static const char* value(const ::autopilot_bridge::ParamSetListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::autopilot_bridge::ParamSetListRequest> should match 
// service_traits::DataType< ::autopilot_bridge::ParamSetList > 
template<>
struct DataType< ::autopilot_bridge::ParamSetListRequest>
{
  static const char* value()
  {
    return DataType< ::autopilot_bridge::ParamSetList >::value();
  }
  static const char* value(const ::autopilot_bridge::ParamSetListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::autopilot_bridge::ParamSetListResponse> should match 
// service_traits::MD5Sum< ::autopilot_bridge::ParamSetList > 
template<>
struct MD5Sum< ::autopilot_bridge::ParamSetListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::autopilot_bridge::ParamSetList >::value();
  }
  static const char* value(const ::autopilot_bridge::ParamSetListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::autopilot_bridge::ParamSetListResponse> should match 
// service_traits::DataType< ::autopilot_bridge::ParamSetList > 
template<>
struct DataType< ::autopilot_bridge::ParamSetListResponse>
{
  static const char* value()
  {
    return DataType< ::autopilot_bridge::ParamSetList >::value();
  }
  static const char* value(const ::autopilot_bridge::ParamSetListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTOPILOT_BRIDGE_MESSAGE_PARAMSETLIST_H
