// Generated by gencpp from file autopilot_bridge/ParamGetList.msg
// DO NOT EDIT!


#ifndef AUTOPILOT_BRIDGE_MESSAGE_PARAMGETLIST_H
#define AUTOPILOT_BRIDGE_MESSAGE_PARAMGETLIST_H

#include <ros/service_traits.h>


#include <autopilot_bridge/ParamGetListRequest.h>
#include <autopilot_bridge/ParamGetListResponse.h>


namespace autopilot_bridge
{

struct ParamGetList
{

typedef ParamGetListRequest Request;
typedef ParamGetListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ParamGetList
} // namespace autopilot_bridge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::autopilot_bridge::ParamGetList > {
  static const char* value()
  {
    return "e2cef5924ec02ac5c653b10adb157290";
  }

  static const char* value(const ::autopilot_bridge::ParamGetList&) { return value(); }
};

template<>
struct DataType< ::autopilot_bridge::ParamGetList > {
  static const char* value()
  {
    return "autopilot_bridge/ParamGetList";
  }

  static const char* value(const ::autopilot_bridge::ParamGetList&) { return value(); }
};


// service_traits::MD5Sum< ::autopilot_bridge::ParamGetListRequest> should match 
// service_traits::MD5Sum< ::autopilot_bridge::ParamGetList > 
template<>
struct MD5Sum< ::autopilot_bridge::ParamGetListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::autopilot_bridge::ParamGetList >::value();
  }
  static const char* value(const ::autopilot_bridge::ParamGetListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::autopilot_bridge::ParamGetListRequest> should match 
// service_traits::DataType< ::autopilot_bridge::ParamGetList > 
template<>
struct DataType< ::autopilot_bridge::ParamGetListRequest>
{
  static const char* value()
  {
    return DataType< ::autopilot_bridge::ParamGetList >::value();
  }
  static const char* value(const ::autopilot_bridge::ParamGetListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::autopilot_bridge::ParamGetListResponse> should match 
// service_traits::MD5Sum< ::autopilot_bridge::ParamGetList > 
template<>
struct MD5Sum< ::autopilot_bridge::ParamGetListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::autopilot_bridge::ParamGetList >::value();
  }
  static const char* value(const ::autopilot_bridge::ParamGetListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::autopilot_bridge::ParamGetListResponse> should match 
// service_traits::DataType< ::autopilot_bridge::ParamGetList > 
template<>
struct DataType< ::autopilot_bridge::ParamGetListResponse>
{
  static const char* value()
  {
    return DataType< ::autopilot_bridge::ParamGetList >::value();
  }
  static const char* value(const ::autopilot_bridge::ParamGetListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTOPILOT_BRIDGE_MESSAGE_PARAMGETLIST_H
