// Generated by gencpp from file autopilot_bridge/RallyGetAll.msg
// DO NOT EDIT!


#ifndef AUTOPILOT_BRIDGE_MESSAGE_RALLYGETALL_H
#define AUTOPILOT_BRIDGE_MESSAGE_RALLYGETALL_H

#include <ros/service_traits.h>


#include <autopilot_bridge/RallyGetAllRequest.h>
#include <autopilot_bridge/RallyGetAllResponse.h>


namespace autopilot_bridge
{

struct RallyGetAll
{

typedef RallyGetAllRequest Request;
typedef RallyGetAllResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RallyGetAll
} // namespace autopilot_bridge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::autopilot_bridge::RallyGetAll > {
  static const char* value()
  {
    return "a2828381673d0b45c532f4eea68ab4e0";
  }

  static const char* value(const ::autopilot_bridge::RallyGetAll&) { return value(); }
};

template<>
struct DataType< ::autopilot_bridge::RallyGetAll > {
  static const char* value()
  {
    return "autopilot_bridge/RallyGetAll";
  }

  static const char* value(const ::autopilot_bridge::RallyGetAll&) { return value(); }
};


// service_traits::MD5Sum< ::autopilot_bridge::RallyGetAllRequest> should match 
// service_traits::MD5Sum< ::autopilot_bridge::RallyGetAll > 
template<>
struct MD5Sum< ::autopilot_bridge::RallyGetAllRequest>
{
  static const char* value()
  {
    return MD5Sum< ::autopilot_bridge::RallyGetAll >::value();
  }
  static const char* value(const ::autopilot_bridge::RallyGetAllRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::autopilot_bridge::RallyGetAllRequest> should match 
// service_traits::DataType< ::autopilot_bridge::RallyGetAll > 
template<>
struct DataType< ::autopilot_bridge::RallyGetAllRequest>
{
  static const char* value()
  {
    return DataType< ::autopilot_bridge::RallyGetAll >::value();
  }
  static const char* value(const ::autopilot_bridge::RallyGetAllRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::autopilot_bridge::RallyGetAllResponse> should match 
// service_traits::MD5Sum< ::autopilot_bridge::RallyGetAll > 
template<>
struct MD5Sum< ::autopilot_bridge::RallyGetAllResponse>
{
  static const char* value()
  {
    return MD5Sum< ::autopilot_bridge::RallyGetAll >::value();
  }
  static const char* value(const ::autopilot_bridge::RallyGetAllResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::autopilot_bridge::RallyGetAllResponse> should match 
// service_traits::DataType< ::autopilot_bridge::RallyGetAll > 
template<>
struct DataType< ::autopilot_bridge::RallyGetAllResponse>
{
  static const char* value()
  {
    return DataType< ::autopilot_bridge::RallyGetAll >::value();
  }
  static const char* value(const ::autopilot_bridge::RallyGetAllResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTOPILOT_BRIDGE_MESSAGE_RALLYGETALL_H
