// Generated by gencpp from file autopilot_bridge/RallySetAll.msg
// DO NOT EDIT!


#ifndef AUTOPILOT_BRIDGE_MESSAGE_RALLYSETALL_H
#define AUTOPILOT_BRIDGE_MESSAGE_RALLYSETALL_H

#include <ros/service_traits.h>


#include <autopilot_bridge/RallySetAllRequest.h>
#include <autopilot_bridge/RallySetAllResponse.h>


namespace autopilot_bridge
{

struct RallySetAll
{

typedef RallySetAllRequest Request;
typedef RallySetAllResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RallySetAll
} // namespace autopilot_bridge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::autopilot_bridge::RallySetAll > {
  static const char* value()
  {
    return "3b61b953a20eeadfbf79e0c55e54fdea";
  }

  static const char* value(const ::autopilot_bridge::RallySetAll&) { return value(); }
};

template<>
struct DataType< ::autopilot_bridge::RallySetAll > {
  static const char* value()
  {
    return "autopilot_bridge/RallySetAll";
  }

  static const char* value(const ::autopilot_bridge::RallySetAll&) { return value(); }
};


// service_traits::MD5Sum< ::autopilot_bridge::RallySetAllRequest> should match 
// service_traits::MD5Sum< ::autopilot_bridge::RallySetAll > 
template<>
struct MD5Sum< ::autopilot_bridge::RallySetAllRequest>
{
  static const char* value()
  {
    return MD5Sum< ::autopilot_bridge::RallySetAll >::value();
  }
  static const char* value(const ::autopilot_bridge::RallySetAllRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::autopilot_bridge::RallySetAllRequest> should match 
// service_traits::DataType< ::autopilot_bridge::RallySetAll > 
template<>
struct DataType< ::autopilot_bridge::RallySetAllRequest>
{
  static const char* value()
  {
    return DataType< ::autopilot_bridge::RallySetAll >::value();
  }
  static const char* value(const ::autopilot_bridge::RallySetAllRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::autopilot_bridge::RallySetAllResponse> should match 
// service_traits::MD5Sum< ::autopilot_bridge::RallySetAll > 
template<>
struct MD5Sum< ::autopilot_bridge::RallySetAllResponse>
{
  static const char* value()
  {
    return MD5Sum< ::autopilot_bridge::RallySetAll >::value();
  }
  static const char* value(const ::autopilot_bridge::RallySetAllResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::autopilot_bridge::RallySetAllResponse> should match 
// service_traits::DataType< ::autopilot_bridge::RallySetAll > 
template<>
struct DataType< ::autopilot_bridge::RallySetAllResponse>
{
  static const char* value()
  {
    return DataType< ::autopilot_bridge::RallySetAll >::value();
  }
  static const char* value(const ::autopilot_bridge::RallySetAllResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTOPILOT_BRIDGE_MESSAGE_RALLYSETALL_H
