// Generated by gencpp from file autopilot_bridge/ReqPrevNMsgsResponse.msg
// DO NOT EDIT!


#ifndef AUTOPILOT_BRIDGE_MESSAGE_REQPREVNMSGSRESPONSE_H
#define AUTOPILOT_BRIDGE_MESSAGE_REQPREVNMSGSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <autopilot_bridge/AutoPilotMsg.h>

namespace autopilot_bridge
{
template <class ContainerAllocator>
struct ReqPrevNMsgsResponse_
{
  typedef ReqPrevNMsgsResponse_<ContainerAllocator> Type;

  ReqPrevNMsgsResponse_()
    : msgs()  {
    }
  ReqPrevNMsgsResponse_(const ContainerAllocator& _alloc)
    : msgs(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::autopilot_bridge::AutoPilotMsg_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::autopilot_bridge::AutoPilotMsg_<ContainerAllocator> >::other >  _msgs_type;
  _msgs_type msgs;




  typedef boost::shared_ptr< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReqPrevNMsgsResponse_

typedef ::autopilot_bridge::ReqPrevNMsgsResponse_<std::allocator<void> > ReqPrevNMsgsResponse;

typedef boost::shared_ptr< ::autopilot_bridge::ReqPrevNMsgsResponse > ReqPrevNMsgsResponsePtr;
typedef boost::shared_ptr< ::autopilot_bridge::ReqPrevNMsgsResponse const> ReqPrevNMsgsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace autopilot_bridge

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'autopilot_bridge': ['/home/osboxes/ACS/acs_ros_ws/src/autopilot_bridge/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b83e643d817366665bc7d105b0ffecd6";
  }

  static const char* value(const ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb83e643d81736666ULL;
  static const uint64_t static_value2 = 0x5bc7d105b0ffecd6ULL;
};

template<class ContainerAllocator>
struct DataType< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autopilot_bridge/ReqPrevNMsgsResponse";
  }

  static const char* value(const ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "AutoPilotMsg[] msgs\n\
\n\
\n\
================================================================================\n\
MSG: autopilot_bridge/AutoPilotMsg\n\
uint32  seq\n\
string  text\n\
";
  }

  static const char* value(const ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msgs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ReqPrevNMsgsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autopilot_bridge::ReqPrevNMsgsResponse_<ContainerAllocator>& v)
  {
    s << indent << "msgs[]" << std::endl;
    for (size_t i = 0; i < v.msgs.size(); ++i)
    {
      s << indent << "  msgs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::autopilot_bridge::AutoPilotMsg_<ContainerAllocator> >::stream(s, indent + "    ", v.msgs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOPILOT_BRIDGE_MESSAGE_REQPREVNMSGSRESPONSE_H
