// Generated by gencpp from file autopilot_bridge/ReqPrevNMsgs.msg
// DO NOT EDIT!


#ifndef AUTOPILOT_BRIDGE_MESSAGE_REQPREVNMSGS_H
#define AUTOPILOT_BRIDGE_MESSAGE_REQPREVNMSGS_H

#include <ros/service_traits.h>


#include <autopilot_bridge/ReqPrevNMsgsRequest.h>
#include <autopilot_bridge/ReqPrevNMsgsResponse.h>


namespace autopilot_bridge
{

struct ReqPrevNMsgs
{

typedef ReqPrevNMsgsRequest Request;
typedef ReqPrevNMsgsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReqPrevNMsgs
} // namespace autopilot_bridge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::autopilot_bridge::ReqPrevNMsgs > {
  static const char* value()
  {
    return "5b9a3726344783db5cbe1607b04eb17e";
  }

  static const char* value(const ::autopilot_bridge::ReqPrevNMsgs&) { return value(); }
};

template<>
struct DataType< ::autopilot_bridge::ReqPrevNMsgs > {
  static const char* value()
  {
    return "autopilot_bridge/ReqPrevNMsgs";
  }

  static const char* value(const ::autopilot_bridge::ReqPrevNMsgs&) { return value(); }
};


// service_traits::MD5Sum< ::autopilot_bridge::ReqPrevNMsgsRequest> should match 
// service_traits::MD5Sum< ::autopilot_bridge::ReqPrevNMsgs > 
template<>
struct MD5Sum< ::autopilot_bridge::ReqPrevNMsgsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::autopilot_bridge::ReqPrevNMsgs >::value();
  }
  static const char* value(const ::autopilot_bridge::ReqPrevNMsgsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::autopilot_bridge::ReqPrevNMsgsRequest> should match 
// service_traits::DataType< ::autopilot_bridge::ReqPrevNMsgs > 
template<>
struct DataType< ::autopilot_bridge::ReqPrevNMsgsRequest>
{
  static const char* value()
  {
    return DataType< ::autopilot_bridge::ReqPrevNMsgs >::value();
  }
  static const char* value(const ::autopilot_bridge::ReqPrevNMsgsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::autopilot_bridge::ReqPrevNMsgsResponse> should match 
// service_traits::MD5Sum< ::autopilot_bridge::ReqPrevNMsgs > 
template<>
struct MD5Sum< ::autopilot_bridge::ReqPrevNMsgsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::autopilot_bridge::ReqPrevNMsgs >::value();
  }
  static const char* value(const ::autopilot_bridge::ReqPrevNMsgsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::autopilot_bridge::ReqPrevNMsgsResponse> should match 
// service_traits::DataType< ::autopilot_bridge::ReqPrevNMsgs > 
template<>
struct DataType< ::autopilot_bridge::ReqPrevNMsgsResponse>
{
  static const char* value()
  {
    return DataType< ::autopilot_bridge::ReqPrevNMsgs >::value();
  }
  static const char* value(const ::autopilot_bridge::ReqPrevNMsgsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTOPILOT_BRIDGE_MESSAGE_REQPREVNMSGS_H
