// Generated by gencpp from file autopilot_bridge/SlaveSetup.msg
// DO NOT EDIT!


#ifndef AUTOPILOT_BRIDGE_MESSAGE_SLAVESETUP_H
#define AUTOPILOT_BRIDGE_MESSAGE_SLAVESETUP_H

#include <ros/service_traits.h>


#include <autopilot_bridge/SlaveSetupRequest.h>
#include <autopilot_bridge/SlaveSetupResponse.h>


namespace autopilot_bridge
{

struct SlaveSetup
{

typedef SlaveSetupRequest Request;
typedef SlaveSetupResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SlaveSetup
} // namespace autopilot_bridge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::autopilot_bridge::SlaveSetup > {
  static const char* value()
  {
    return "d5924e2477b62d263f4cdf77d9e962e5";
  }

  static const char* value(const ::autopilot_bridge::SlaveSetup&) { return value(); }
};

template<>
struct DataType< ::autopilot_bridge::SlaveSetup > {
  static const char* value()
  {
    return "autopilot_bridge/SlaveSetup";
  }

  static const char* value(const ::autopilot_bridge::SlaveSetup&) { return value(); }
};


// service_traits::MD5Sum< ::autopilot_bridge::SlaveSetupRequest> should match 
// service_traits::MD5Sum< ::autopilot_bridge::SlaveSetup > 
template<>
struct MD5Sum< ::autopilot_bridge::SlaveSetupRequest>
{
  static const char* value()
  {
    return MD5Sum< ::autopilot_bridge::SlaveSetup >::value();
  }
  static const char* value(const ::autopilot_bridge::SlaveSetupRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::autopilot_bridge::SlaveSetupRequest> should match 
// service_traits::DataType< ::autopilot_bridge::SlaveSetup > 
template<>
struct DataType< ::autopilot_bridge::SlaveSetupRequest>
{
  static const char* value()
  {
    return DataType< ::autopilot_bridge::SlaveSetup >::value();
  }
  static const char* value(const ::autopilot_bridge::SlaveSetupRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::autopilot_bridge::SlaveSetupResponse> should match 
// service_traits::MD5Sum< ::autopilot_bridge::SlaveSetup > 
template<>
struct MD5Sum< ::autopilot_bridge::SlaveSetupResponse>
{
  static const char* value()
  {
    return MD5Sum< ::autopilot_bridge::SlaveSetup >::value();
  }
  static const char* value(const ::autopilot_bridge::SlaveSetupResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::autopilot_bridge::SlaveSetupResponse> should match 
// service_traits::DataType< ::autopilot_bridge::SlaveSetup > 
template<>
struct DataType< ::autopilot_bridge::SlaveSetupResponse>
{
  static const char* value()
  {
    return DataType< ::autopilot_bridge::SlaveSetup >::value();
  }
  static const char* value(const ::autopilot_bridge::SlaveSetupResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTOPILOT_BRIDGE_MESSAGE_SLAVESETUP_H
