// Generated by gencpp from file autopilot_bridge/WPSetAll.msg
// DO NOT EDIT!


#ifndef AUTOPILOT_BRIDGE_MESSAGE_WPSETALL_H
#define AUTOPILOT_BRIDGE_MESSAGE_WPSETALL_H

#include <ros/service_traits.h>


#include <autopilot_bridge/WPSetAllRequest.h>
#include <autopilot_bridge/WPSetAllResponse.h>


namespace autopilot_bridge
{

struct WPSetAll
{

typedef WPSetAllRequest Request;
typedef WPSetAllResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WPSetAll
} // namespace autopilot_bridge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::autopilot_bridge::WPSetAll > {
  static const char* value()
  {
    return "ca7cf06c1f77e9786e36687dbdde93e2";
  }

  static const char* value(const ::autopilot_bridge::WPSetAll&) { return value(); }
};

template<>
struct DataType< ::autopilot_bridge::WPSetAll > {
  static const char* value()
  {
    return "autopilot_bridge/WPSetAll";
  }

  static const char* value(const ::autopilot_bridge::WPSetAll&) { return value(); }
};


// service_traits::MD5Sum< ::autopilot_bridge::WPSetAllRequest> should match 
// service_traits::MD5Sum< ::autopilot_bridge::WPSetAll > 
template<>
struct MD5Sum< ::autopilot_bridge::WPSetAllRequest>
{
  static const char* value()
  {
    return MD5Sum< ::autopilot_bridge::WPSetAll >::value();
  }
  static const char* value(const ::autopilot_bridge::WPSetAllRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::autopilot_bridge::WPSetAllRequest> should match 
// service_traits::DataType< ::autopilot_bridge::WPSetAll > 
template<>
struct DataType< ::autopilot_bridge::WPSetAllRequest>
{
  static const char* value()
  {
    return DataType< ::autopilot_bridge::WPSetAll >::value();
  }
  static const char* value(const ::autopilot_bridge::WPSetAllRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::autopilot_bridge::WPSetAllResponse> should match 
// service_traits::MD5Sum< ::autopilot_bridge::WPSetAll > 
template<>
struct MD5Sum< ::autopilot_bridge::WPSetAllResponse>
{
  static const char* value()
  {
    return MD5Sum< ::autopilot_bridge::WPSetAll >::value();
  }
  static const char* value(const ::autopilot_bridge::WPSetAllResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::autopilot_bridge::WPSetAllResponse> should match 
// service_traits::DataType< ::autopilot_bridge::WPSetAll > 
template<>
struct DataType< ::autopilot_bridge::WPSetAllResponse>
{
  static const char* value()
  {
    return DataType< ::autopilot_bridge::WPSetAll >::value();
  }
  static const char* value(const ::autopilot_bridge::WPSetAllResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTOPILOT_BRIDGE_MESSAGE_WPSETALL_H
