(cl:defpackage ap_srvs-srv
  (:use )
  (:export
   "SETBEHAVIOR"
   "<SETBEHAVIOR-REQUEST>"
   "SETBEHAVIOR-REQUEST"
   "<SETBEHAVIOR-RESPONSE>"
   "SETBEHAVIOR-RESPONSE"
   "REGISTERBEHAVIOR"
   "<REGISTERBEHAVIOR-REQUEST>"
   "REGISTERBEHAVIOR-REQUEST"
   "<REGISTERBEHAVIOR-RESPONSE>"
   "REGISTERBEHAVIOR-RESPONSE"
   "SETINTEGER"
   "<SETINTEGER-REQUEST>"
   "SETINTEGER-REQUEST"
   "<SETINTEGER-RESPONSE>"
   "SETINTEGER-RESPONSE"
   "SETBOOLEAN"
   "<SETBOOLEAN-REQUEST>"
   "SETBOOLEAN-REQUEST"
   "<SETBOOLEAN-RESPONSE>"
   "SETBOOLEAN-RESPONSE"
  ))

