(cl:in-package autopilot_bridge-msg)
(cl:export '(HEADER-VAL
          HEADER
          MODE-VAL
          MODE
          ARMED-VAL
          ARMED
          AHRS_OK-VAL
          AHRS_OK
          ALT_REL-VAL
          ALT_REL
          AS_OK-VAL
          AS_OK
          AS_READ-VAL
          AS_READ
          FENCE_STATUS-VAL
          FENCE_STATUS
          GPS_OK-VAL
          GPS_OK
          GPS_SATS-VAL
          GPS_SATS
          GPS_EPH-VAL
          GPS_EPH
          INS_OK-VAL
          INS_OK
          MAG_OK-VAL
          MAG_OK
          MIS_CUR-VAL
          MIS_CUR
          PWR_OK-VAL
          PWR_OK
          PWR_BATT_REM-VAL
          PWR_BATT_REM
          PWR_BATT_VCC-VAL
          PWR_BATT_VCC
          PWR_BATT_CUR-VAL
          PWR_BATT_CUR
))