# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from autopilot_bridge/GeoPose.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import autopilot_bridge.msg
import geometry_msgs.msg

class GeoPose(genpy.Message):
  _md5sum = "a73a1efca4f7df92e709875c74f317f9"
  _type = "autopilot_bridge/GeoPose"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# 3-D point using lat/lon/alt, with two altitude options
GeoPoint position

# Quaternion orientation
geometry_msgs/Quaternion orientation

================================================================================
MSG: autopilot_bridge/GeoPoint
# WGS84 latitude, longitude, and MSL altitude
float64 lat
float64 lon
float64 alt

# Relative altitude (custom definable, but generally set w.r.t. some home point)
float64 rel_alt

# Flag field for which altitudes are valid
bool using_alt
bool using_rel_alt

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['position','orientation']
  _slot_types = ['autopilot_bridge/GeoPoint','geometry_msgs/Quaternion']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       position,orientation

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GeoPose, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.position is None:
        self.position = autopilot_bridge.msg.GeoPoint()
      if self.orientation is None:
        self.orientation = geometry_msgs.msg.Quaternion()
    else:
      self.position = autopilot_bridge.msg.GeoPoint()
      self.orientation = geometry_msgs.msg.Quaternion()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4d2B4d.pack(_x.position.lat, _x.position.lon, _x.position.alt, _x.position.rel_alt, _x.position.using_alt, _x.position.using_rel_alt, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.position is None:
        self.position = autopilot_bridge.msg.GeoPoint()
      if self.orientation is None:
        self.orientation = geometry_msgs.msg.Quaternion()
      end = 0
      _x = self
      start = end
      end += 66
      (_x.position.lat, _x.position.lon, _x.position.alt, _x.position.rel_alt, _x.position.using_alt, _x.position.using_rel_alt, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.orientation.w,) = _struct_4d2B4d.unpack(str[start:end])
      self.position.using_alt = bool(self.position.using_alt)
      self.position.using_rel_alt = bool(self.position.using_rel_alt)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4d2B4d.pack(_x.position.lat, _x.position.lon, _x.position.alt, _x.position.rel_alt, _x.position.using_alt, _x.position.using_rel_alt, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.position is None:
        self.position = autopilot_bridge.msg.GeoPoint()
      if self.orientation is None:
        self.orientation = geometry_msgs.msg.Quaternion()
      end = 0
      _x = self
      start = end
      end += 66
      (_x.position.lat, _x.position.lon, _x.position.alt, _x.position.rel_alt, _x.position.using_alt, _x.position.using_rel_alt, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.orientation.w,) = _struct_4d2B4d.unpack(str[start:end])
      self.position.using_alt = bool(self.position.using_alt)
      self.position.using_rel_alt = bool(self.position.using_rel_alt)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4d2B4d = struct.Struct("<4d2B4d")
