# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from autopilot_bridge/Rallypoint.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Rallypoint(genpy.Message):
  _md5sum = "18ae3a5294644e7830f081afbc682a08"
  _type = "autopilot_bridge/Rallypoint"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 lat
float64 lon
float64 alt
float64 break_alt
float64 land_dir
uint8 flags
"""
  __slots__ = ['lat','lon','alt','break_alt','land_dir','flags']
  _slot_types = ['float64','float64','float64','float64','float64','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       lat,lon,alt,break_alt,land_dir,flags

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Rallypoint, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.lat is None:
        self.lat = 0.
      if self.lon is None:
        self.lon = 0.
      if self.alt is None:
        self.alt = 0.
      if self.break_alt is None:
        self.break_alt = 0.
      if self.land_dir is None:
        self.land_dir = 0.
      if self.flags is None:
        self.flags = 0
    else:
      self.lat = 0.
      self.lon = 0.
      self.alt = 0.
      self.break_alt = 0.
      self.land_dir = 0.
      self.flags = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_5dB.pack(_x.lat, _x.lon, _x.alt, _x.break_alt, _x.land_dir, _x.flags))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 41
      (_x.lat, _x.lon, _x.alt, _x.break_alt, _x.land_dir, _x.flags,) = _struct_5dB.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_5dB.pack(_x.lat, _x.lon, _x.alt, _x.break_alt, _x.land_dir, _x.flags))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 41
      (_x.lat, _x.lon, _x.alt, _x.break_alt, _x.land_dir, _x.flags,) = _struct_5dB.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_5dB = struct.Struct("<5dB")
