# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from autopilot_bridge/WeatherData.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class WeatherData(genpy.Message):
  _md5sum = "ad6ecb730008621b85e84342a94f123f"
  _type = "autopilot_bridge/WeatherData"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 baro_millibars
float32 temp_C
float32 wind_mph
float32 wind_direction
"""
  __slots__ = ['baro_millibars','temp_C','wind_mph','wind_direction']
  _slot_types = ['float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       baro_millibars,temp_C,wind_mph,wind_direction

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WeatherData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.baro_millibars is None:
        self.baro_millibars = 0.
      if self.temp_C is None:
        self.temp_C = 0.
      if self.wind_mph is None:
        self.wind_mph = 0.
      if self.wind_direction is None:
        self.wind_direction = 0.
    else:
      self.baro_millibars = 0.
      self.temp_C = 0.
      self.wind_mph = 0.
      self.wind_direction = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4f.pack(_x.baro_millibars, _x.temp_C, _x.wind_mph, _x.wind_direction))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.baro_millibars, _x.temp_C, _x.wind_mph, _x.wind_direction,) = _struct_4f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4f.pack(_x.baro_millibars, _x.temp_C, _x.wind_mph, _x.wind_direction))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.baro_millibars, _x.temp_C, _x.wind_mph, _x.wind_direction,) = _struct_4f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4f = struct.Struct("<4f")
