// Generated by gencpp from file ap_msgs/BehaviorParameters.msg
// DO NOT EDIT!


#ifndef AP_MSGS_MESSAGE_BEHAVIORPARAMETERS_H
#define AP_MSGS_MESSAGE_BEHAVIORPARAMETERS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ap_msgs
{
template <class ContainerAllocator>
struct BehaviorParameters_
{
  typedef BehaviorParameters_<ContainerAllocator> Type;

  BehaviorParameters_()
    : id(0)
    , params()  {
    }
  BehaviorParameters_(const ContainerAllocator& _alloc)
    : id(0)
    , params(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _params_type;
  _params_type params;




  typedef boost::shared_ptr< ::ap_msgs::BehaviorParameters_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ap_msgs::BehaviorParameters_<ContainerAllocator> const> ConstPtr;

}; // struct BehaviorParameters_

typedef ::ap_msgs::BehaviorParameters_<std::allocator<void> > BehaviorParameters;

typedef boost::shared_ptr< ::ap_msgs::BehaviorParameters > BehaviorParametersPtr;
typedef boost::shared_ptr< ::ap_msgs::BehaviorParameters const> BehaviorParametersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ap_msgs::BehaviorParameters_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ap_msgs::BehaviorParameters_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ap_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'ap_msgs': ['/home/osboxes/ACS/acs_ros_ws/src/autonomy-payload/ap_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'autopilot_bridge': ['/home/osboxes/ACS/acs_ros_ws/src/autopilot_bridge/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ap_msgs::BehaviorParameters_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ap_msgs::BehaviorParameters_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ap_msgs::BehaviorParameters_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ap_msgs::BehaviorParameters_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ap_msgs::BehaviorParameters_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ap_msgs::BehaviorParameters_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ap_msgs::BehaviorParameters_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af1234d6bfae4749ec1409770312d0f5";
  }

  static const char* value(const ::ap_msgs::BehaviorParameters_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf1234d6bfae4749ULL;
  static const uint64_t static_value2 = 0xec1409770312d0f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::ap_msgs::BehaviorParameters_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ap_msgs/BehaviorParameters";
  }

  static const char* value(const ::ap_msgs::BehaviorParameters_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ap_msgs::BehaviorParameters_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n\
uint8[] params\n\
";
  }

  static const char* value(const ::ap_msgs::BehaviorParameters_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ap_msgs::BehaviorParameters_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.params);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct BehaviorParameters_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ap_msgs::BehaviorParameters_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ap_msgs::BehaviorParameters_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "params[]" << std::endl;
    for (size_t i = 0; i < v.params.size(); ++i)
    {
      s << indent << "  params[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.params[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AP_MSGS_MESSAGE_BEHAVIORPARAMETERS_H
