// Generated by gencpp from file ap_msgs/MsgStat.msg
// DO NOT EDIT!


#ifndef AP_MSGS_MESSAGE_MSGSTAT_H
#define AP_MSGS_MESSAGE_MSGSTAT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ap_msgs
{
template <class ContainerAllocator>
struct MsgStat_
{
  typedef MsgStat_<ContainerAllocator> Type;

  MsgStat_()
    : id(0)
    , count(0)
    , latency(0.0)  {
    }
  MsgStat_(const ContainerAllocator& _alloc)
    : id(0)
    , count(0)
    , latency(0.0)  {
  (void)_alloc;
    }



   typedef uint16_t _id_type;
  _id_type id;

   typedef uint32_t _count_type;
  _count_type count;

   typedef double _latency_type;
  _latency_type latency;




  typedef boost::shared_ptr< ::ap_msgs::MsgStat_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ap_msgs::MsgStat_<ContainerAllocator> const> ConstPtr;

}; // struct MsgStat_

typedef ::ap_msgs::MsgStat_<std::allocator<void> > MsgStat;

typedef boost::shared_ptr< ::ap_msgs::MsgStat > MsgStatPtr;
typedef boost::shared_ptr< ::ap_msgs::MsgStat const> MsgStatConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ap_msgs::MsgStat_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ap_msgs::MsgStat_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ap_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'ap_msgs': ['/home/osboxes/ACS/acs_ros_ws/src/autonomy-payload/ap_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'autopilot_bridge': ['/home/osboxes/ACS/acs_ros_ws/src/autopilot_bridge/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ap_msgs::MsgStat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ap_msgs::MsgStat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ap_msgs::MsgStat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ap_msgs::MsgStat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ap_msgs::MsgStat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ap_msgs::MsgStat_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ap_msgs::MsgStat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b03b0e59c2cf7eb753d1ca3563758d8";
  }

  static const char* value(const ::ap_msgs::MsgStat_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b03b0e59c2cf7ebULL;
  static const uint64_t static_value2 = 0x753d1ca3563758d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::ap_msgs::MsgStat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ap_msgs/MsgStat";
  }

  static const char* value(const ::ap_msgs::MsgStat_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ap_msgs::MsgStat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 id\n\
uint32 count\n\
float64 latency\n\
";
  }

  static const char* value(const ::ap_msgs::MsgStat_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ap_msgs::MsgStat_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.count);
      stream.next(m.latency);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MsgStat_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ap_msgs::MsgStat_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ap_msgs::MsgStat_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.id);
    s << indent << "count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.count);
    s << indent << "latency: ";
    Printer<double>::stream(s, indent + "  ", v.latency);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AP_MSGS_MESSAGE_MSGSTAT_H
