// Generated by gencpp from file ap_srvs/RegisterBehaviorResponse.msg
// DO NOT EDIT!


#ifndef AP_SRVS_MESSAGE_REGISTERBEHAVIORRESPONSE_H
#define AP_SRVS_MESSAGE_REGISTERBEHAVIORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ap_srvs
{
template <class ContainerAllocator>
struct RegisterBehaviorResponse_
{
  typedef RegisterBehaviorResponse_<ContainerAllocator> Type;

  RegisterBehaviorResponse_()
    : result(false)  {
    }
  RegisterBehaviorResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;




  typedef boost::shared_ptr< ::ap_srvs::RegisterBehaviorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ap_srvs::RegisterBehaviorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RegisterBehaviorResponse_

typedef ::ap_srvs::RegisterBehaviorResponse_<std::allocator<void> > RegisterBehaviorResponse;

typedef boost::shared_ptr< ::ap_srvs::RegisterBehaviorResponse > RegisterBehaviorResponsePtr;
typedef boost::shared_ptr< ::ap_srvs::RegisterBehaviorResponse const> RegisterBehaviorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ap_srvs::RegisterBehaviorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ap_srvs::RegisterBehaviorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ap_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'ap_msgs': ['/home/osboxes/ACS/acs_ros_ws/src/autonomy-payload/ap_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'autopilot_bridge': ['/home/osboxes/ACS/acs_ros_ws/src/autopilot_bridge/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ap_srvs::RegisterBehaviorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ap_srvs::RegisterBehaviorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ap_srvs::RegisterBehaviorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ap_srvs::RegisterBehaviorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ap_srvs::RegisterBehaviorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ap_srvs::RegisterBehaviorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ap_srvs::RegisterBehaviorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::ap_srvs::RegisterBehaviorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::ap_srvs::RegisterBehaviorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ap_srvs/RegisterBehaviorResponse";
  }

  static const char* value(const ::ap_srvs::RegisterBehaviorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ap_srvs::RegisterBehaviorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n\
\n\
";
  }

  static const char* value(const ::ap_srvs::RegisterBehaviorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ap_srvs::RegisterBehaviorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct RegisterBehaviorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ap_srvs::RegisterBehaviorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ap_srvs::RegisterBehaviorResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AP_SRVS_MESSAGE_REGISTERBEHAVIORRESPONSE_H
