// Generated by gencpp from file ap_srvs/RegisterBehavior.msg
// DO NOT EDIT!


#ifndef AP_SRVS_MESSAGE_REGISTERBEHAVIOR_H
#define AP_SRVS_MESSAGE_REGISTERBEHAVIOR_H

#include <ros/service_traits.h>


#include <ap_srvs/RegisterBehaviorRequest.h>
#include <ap_srvs/RegisterBehaviorResponse.h>


namespace ap_srvs
{

struct RegisterBehavior
{

typedef RegisterBehaviorRequest Request;
typedef RegisterBehaviorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RegisterBehavior
} // namespace ap_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ap_srvs::RegisterBehavior > {
  static const char* value()
  {
    return "1e7cf8b044a2fb2667fbc9a807ca43da";
  }

  static const char* value(const ::ap_srvs::RegisterBehavior&) { return value(); }
};

template<>
struct DataType< ::ap_srvs::RegisterBehavior > {
  static const char* value()
  {
    return "ap_srvs/RegisterBehavior";
  }

  static const char* value(const ::ap_srvs::RegisterBehavior&) { return value(); }
};


// service_traits::MD5Sum< ::ap_srvs::RegisterBehaviorRequest> should match 
// service_traits::MD5Sum< ::ap_srvs::RegisterBehavior > 
template<>
struct MD5Sum< ::ap_srvs::RegisterBehaviorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ap_srvs::RegisterBehavior >::value();
  }
  static const char* value(const ::ap_srvs::RegisterBehaviorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ap_srvs::RegisterBehaviorRequest> should match 
// service_traits::DataType< ::ap_srvs::RegisterBehavior > 
template<>
struct DataType< ::ap_srvs::RegisterBehaviorRequest>
{
  static const char* value()
  {
    return DataType< ::ap_srvs::RegisterBehavior >::value();
  }
  static const char* value(const ::ap_srvs::RegisterBehaviorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ap_srvs::RegisterBehaviorResponse> should match 
// service_traits::MD5Sum< ::ap_srvs::RegisterBehavior > 
template<>
struct MD5Sum< ::ap_srvs::RegisterBehaviorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ap_srvs::RegisterBehavior >::value();
  }
  static const char* value(const ::ap_srvs::RegisterBehaviorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ap_srvs::RegisterBehaviorResponse> should match 
// service_traits::DataType< ::ap_srvs::RegisterBehavior > 
template<>
struct DataType< ::ap_srvs::RegisterBehaviorResponse>
{
  static const char* value()
  {
    return DataType< ::ap_srvs::RegisterBehavior >::value();
  }
  static const char* value(const ::ap_srvs::RegisterBehaviorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AP_SRVS_MESSAGE_REGISTERBEHAVIOR_H
