// Generated by gencpp from file ap_srvs/SetBehaviorRequest.msg
// DO NOT EDIT!


#ifndef AP_SRVS_MESSAGE_SETBEHAVIORREQUEST_H
#define AP_SRVS_MESSAGE_SETBEHAVIORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ap_msgs/BehaviorParameters.h>

namespace ap_srvs
{
template <class ContainerAllocator>
struct SetBehaviorRequest_
{
  typedef SetBehaviorRequest_<ContainerAllocator> Type;

  SetBehaviorRequest_()
    : params()  {
    }
  SetBehaviorRequest_(const ContainerAllocator& _alloc)
    : params(_alloc)  {
  (void)_alloc;
    }



   typedef  ::ap_msgs::BehaviorParameters_<ContainerAllocator>  _params_type;
  _params_type params;




  typedef boost::shared_ptr< ::ap_srvs::SetBehaviorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ap_srvs::SetBehaviorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetBehaviorRequest_

typedef ::ap_srvs::SetBehaviorRequest_<std::allocator<void> > SetBehaviorRequest;

typedef boost::shared_ptr< ::ap_srvs::SetBehaviorRequest > SetBehaviorRequestPtr;
typedef boost::shared_ptr< ::ap_srvs::SetBehaviorRequest const> SetBehaviorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ap_srvs::SetBehaviorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ap_srvs::SetBehaviorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ap_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'ap_msgs': ['/home/osboxes/ACS/acs_ros_ws/src/autonomy-payload/ap_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'autopilot_bridge': ['/home/osboxes/ACS/acs_ros_ws/src/autopilot_bridge/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ap_srvs::SetBehaviorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ap_srvs::SetBehaviorRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ap_srvs::SetBehaviorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ap_srvs::SetBehaviorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ap_srvs::SetBehaviorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ap_srvs::SetBehaviorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ap_srvs::SetBehaviorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "482a124051662f4c68d64c120c4e10be";
  }

  static const char* value(const ::ap_srvs::SetBehaviorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x482a124051662f4cULL;
  static const uint64_t static_value2 = 0x68d64c120c4e10beULL;
};

template<class ContainerAllocator>
struct DataType< ::ap_srvs::SetBehaviorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ap_srvs/SetBehaviorRequest";
  }

  static const char* value(const ::ap_srvs::SetBehaviorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ap_srvs::SetBehaviorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ap_msgs/BehaviorParameters params\n\
\n\
================================================================================\n\
MSG: ap_msgs/BehaviorParameters\n\
uint8 id\n\
uint8[] params\n\
";
  }

  static const char* value(const ::ap_srvs::SetBehaviorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ap_srvs::SetBehaviorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.params);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SetBehaviorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ap_srvs::SetBehaviorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ap_srvs::SetBehaviorRequest_<ContainerAllocator>& v)
  {
    s << indent << "params: ";
    s << std::endl;
    Printer< ::ap_msgs::BehaviorParameters_<ContainerAllocator> >::stream(s, indent + "  ", v.params);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AP_SRVS_MESSAGE_SETBEHAVIORREQUEST_H
