// Generated by gencpp from file ap_srvs/SetInteger.msg
// DO NOT EDIT!


#ifndef AP_SRVS_MESSAGE_SETINTEGER_H
#define AP_SRVS_MESSAGE_SETINTEGER_H

#include <ros/service_traits.h>


#include <ap_srvs/SetIntegerRequest.h>
#include <ap_srvs/SetIntegerResponse.h>


namespace ap_srvs
{

struct SetInteger
{

typedef SetIntegerRequest Request;
typedef SetIntegerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInteger
} // namespace ap_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ap_srvs::SetInteger > {
  static const char* value()
  {
    return "9cc7b8927f792e461dca9cd6251d1d23";
  }

  static const char* value(const ::ap_srvs::SetInteger&) { return value(); }
};

template<>
struct DataType< ::ap_srvs::SetInteger > {
  static const char* value()
  {
    return "ap_srvs/SetInteger";
  }

  static const char* value(const ::ap_srvs::SetInteger&) { return value(); }
};


// service_traits::MD5Sum< ::ap_srvs::SetIntegerRequest> should match 
// service_traits::MD5Sum< ::ap_srvs::SetInteger > 
template<>
struct MD5Sum< ::ap_srvs::SetIntegerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ap_srvs::SetInteger >::value();
  }
  static const char* value(const ::ap_srvs::SetIntegerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ap_srvs::SetIntegerRequest> should match 
// service_traits::DataType< ::ap_srvs::SetInteger > 
template<>
struct DataType< ::ap_srvs::SetIntegerRequest>
{
  static const char* value()
  {
    return DataType< ::ap_srvs::SetInteger >::value();
  }
  static const char* value(const ::ap_srvs::SetIntegerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ap_srvs::SetIntegerResponse> should match 
// service_traits::MD5Sum< ::ap_srvs::SetInteger > 
template<>
struct MD5Sum< ::ap_srvs::SetIntegerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ap_srvs::SetInteger >::value();
  }
  static const char* value(const ::ap_srvs::SetIntegerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ap_srvs::SetIntegerResponse> should match 
// service_traits::DataType< ::ap_srvs::SetInteger > 
template<>
struct DataType< ::ap_srvs::SetIntegerResponse>
{
  static const char* value()
  {
    return DataType< ::ap_srvs::SetInteger >::value();
  }
  static const char* value(const ::ap_srvs::SetIntegerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AP_SRVS_MESSAGE_SETINTEGER_H
