(cl:in-package autopilot_bridge-srv)
(cl:export '(TIMEOUT-VAL
          TIMEOUT
          OK-VAL
          OK
          CAP_MISSION_FLOAT-VAL
          CAP_MISSION_FLOAT
          CAP_PARAM_FLOAT-VAL
          CAP_PARAM_FLOAT
          CAP_MISSION_INT-VAL
          CAP_MISSION_INT
          CAP_COMMAND_INT-VAL
          CAP_COMMAND_INT
          CAP_PARAM_UNION-VAL
          CAP_PARAM_UNION
          CAP_FTP-VAL
          CAP_FTP
          CAP_SET_ATTITUDE-VAL
          CAP_SET_ATTITUDE
          CAP_SET_POSITION_LOCAL-VAL
          CAP_SET_POSITION_LOCAL
          CAP_SET_POSITION_GLOBAL-VAL
          CAP_SET_POSITION_GLOBAL
          CAP_TERRAIN-VAL
          CAP_TERRAIN
          CAP_SET_ACTUATOR-VAL
          CAP_SET_ACTUATOR
          FLIGHT_SW-VAL
          FLIGHT_SW
          MIDDLEWARE-VAL
          MIDDLEWARE
          OS_SW-VAL
          OS_SW
          BOARD-VAL
          BOARD
          FLIGHT_CUSTOM-VAL
          FLIGHT_CUSTOM
          MIDDLEWARE_CUSTOM-VAL
          MIDDLEWARE_CUSTOM
          OS_CUSTOM-VAL
          OS_CUSTOM
          VENDOR_ID-VAL
          VENDOR_ID
          PRODUCT_ID-VAL
          PRODUCT_ID
          UID-VAL
          UID
))